version: 0.1
tools:
  definitions:
    - name: foofinder
      runtime: node
      package: trunk_plugin_tutorial
      known_good_version: 1.0.0
lint:
  definitions:
    - name: foofinder
      files: [ALL]
      tools: [foofinder]
#      runtime: node
#      package: trunk_plugin_tutorial
      commands:
        - output: pass_fail
          success_codes: [0,1]
          run: node ${plugin}/findfoo.js ${target}
          read_output_from: stdout
